Dual Phone Hold Test
dephillipsmichael/MotorControl-iOS pull request #1
Opened 2019-08-27 23:11 UTC by dephillipsmichael

The JSON wasn't very complicated, but supporting the whichHand and nextHand functionality with different section step identifiers was confusing.  I tested each scenario and all of them are the correct flow.

2019-08-29 13:53 UTC, DanWebster requested changes
Looks great, few copy changes

2019-08-29 13:53 UTC, DanWebster commented on MotorControl/MotorControl/Resources/RestingKineticTremor.json
> +            "text":"In this activity you will be holding the phone in your lap for 30 seconds. You will do this with each hand.  Goal is to measure your tremors in your hand. Then you’ll hold your ph
```suggestion
            "text":"In this challenge you will be holding the phone while doing 2 activities. The first is to keep your hand still in your lap, the second is to move your arm to touch the tip of your nose with the tip of your finger as accurately as you can. Please perform this activity with both hands if you can.",
```

2019-08-29 13:53 UTC, DanWebster commented on MotorControl/MotorControl/Resources/RestingKineticTremor.json
> +                 "start":"Great job, you are done with the Tremor test."
```suggestion
                 "start":"Great job, you are done with the first part of the Dual Phone Hold test."
```

2019-08-29 13:53 UTC, DanWebster commented on MotorControl/MotorControl/Resources/RestingKineticTremorFirstAttemptjson.json
> +                "text":"While sitting down with your feet resting flat on the floor, you will be holding the phone still in your lap for 30 seconds. You will do this first with one hand and then with
```suggestion
                "text":"While sitting down with your feet resting flat on the floor, please hold the phone still in your lap for 30 seconds. You will do this first with one hand and then with your other hand if you can.",
```

2019-08-29 13:53 UTC, DanWebster commented on MotorControl/MotorControl/Resources/RestingKineticTremorFirstAttemptjson.json
> +                     "start":"Great job, you are done with the Tremor test."
```suggestion
                     "start":"Great job, you are done with the second part of the Dual Phone Hold test."
```

2019-08-31 21:39 UTC, dephillipsmichael commented on MotorControl/MotorControl/Resources/RestingKineticTremor.json
> +                 "start":"Great job, you are done with the Tremor test."
This is actually only shown once at the end, so I'm going to make it "Great job, you are done with the Dual Phone Hold test."

2019-08-31 21:41 UTC, dephillipsmichael commented on MotorControl/MotorControl/Resources/RestingKineticTremorFirstAttemptjson.json
> +                     "start":"Great job, you are done with the Tremor test."
Oh I see the issue here.  That JSON was actually a debugging artifact and not used and is now deleted.  The RestingKineticTremor.json contains both tremor and kinetic tremor.

2019-08-31 21:44 UTC, dephillipsmichael commented
@DanWebster changes made

2019-08-31 22:08 UTC, dephillipsmichael commented
Mergining this in.  I fixed the issues and I need to push up the PKU PR targeting this.

2019-08-31 22:10 UTC, merged